export const EXPORT_COLUMNS = [
  { id: 'arquivo', label: 'Arquivo' },
  { id: 'linhaNF', label: 'Linha NF' },
  { id: 'material', label: 'Material' },
  { id: 'descricao', label: 'Descrição' },
  { id: 'centro', label: 'Centro' },
  { id: 'cfop', label: 'CFOP' },
  { id: 'fornecedor', label: 'Fornecedor' },
  { id: 'empresa', label: 'Empresa' },
  { id: 'numeroNF', label: 'Número NF' },
  { id: 'tipoMaterial', label: 'Tipo Material' },
  { id: 'categoriaNF', label: 'Categoria NF' },
  { id: 'origemMaterial', label: 'Origem Material' },
  { id: 'dataLancamento', label: 'Data Lançamento' },
  { id: 'precoSemFrete', label: 'Preço Unit. s/ Frete' },
  { id: 'precoComFrete', label: 'Preço Unit. c/ Frete' },
  { id: 'valorLiqSemFrete', label: 'V. Liq s/ Frete' },
  { id: 'valorLiqComFrete', label: 'V. Liq c/ Frete' },
  { id: 'valorTotalSemFrete', label: 'Total s/ Frete' },
  { id: 'valorTotalComFrete', label: 'Total c/ Frete' },
  { id: 'quantidade', label: 'Quantidade' },
  { id: 'precoEfetivo', label: 'Preço NF' },
  { id: 'custoPadrao', label: 'Custo SAP' },
  { id: 'variacaoPerc', label: 'Variação %' },
  { id: 'impactoFinanceiro', label: 'Impacto Financeiro' },
  { id: 'tipo', label: 'Tipo' },
  { id: 'icms', label: 'ICMS' },
  { id: 'ipi', label: 'IPI' },
  { id: 'pis', label: 'PIS' },
  { id: 'cofins', label: 'COFINS' },
  { id: 'st', label: 'ST' },
];

export const QUICK_EXPORT_COLUMNS = new Set([
  'material',
  'descricao',
  'centro',
  'cfop',
  'fornecedor',
  'dataLancamento',
  'precoEfetivo',
  'custoPadrao',
  'variacaoPerc',
  'impactoFinanceiro',
  'tipo'
]);
